### ISSUE TITLE
[Enhancement] Create 1 input node for input of values and one output for output of values

### ISSUE THREAD

**Issue by MattL0** [HomeSeer/node-red-contrib-homeseer#1]
The same could be applied to the event node ( now only output). It is more user friendly this way I think. 

The two node we have now can be kept for debugging purpose.

**Comment by spudwebb** [comment]
I think it's better to stick as much as possible to how the devices are represented in HS.
To build this node-red implementation I looked at the nodes for Philips Hue, SmartThings, etc..., and they all use the same node for inputs and outputs
