### ISSUE TITLE
Problem sending a status with specific caracter (&) from node-red

### ISSUE THREAD

**Issue by goldriver2** [HomeSeer/node-red-contrib-homeseer#11]
I entered a ticket in homeseer support but I guess it should have been entered here 

I have a string containing the "&" caracter that i am trying to send to a device status but everything after the "&" caracters gets truncated.

exemple:
msg.payload.status = abcdefg&12345, only abcdefg makes it in the device status, the &12345 gets truncated.

**Comment by spudwebb** [comment]
I think we need to encode the status using encodeURIComponent before sending it to homeseer
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by goldriver2** [comment]
Thanks for looking into this

**Comment by spudwebb** [comment]
This is fixed in 1.0.5
