### ISSUE TITLE
TypeError: Cannot read property ‘log’ of undefined

### ISSUE THREAD

**Issue by tonreproc** [HomeSeer/node-red-contrib-homeseer#13]
I upgraded from 1.2.6 to 1.3.1 and now I cannot read my homeseer devices any more. I am using node-red-contrib-homeseer version 1.0.5

The server is set up all right and the Device and Feature are found by the node.

![2021-04-10_143028](https://user-images.githubusercontent.com/17249402/114314037-68c1d600-9af9-11eb-978d-b8256c63263a.png)

Nothing shows up in de catch/debug window, only the same message as before: "TypeError: Cannot read property 'log' of undefined"

![2021-04-11_120852](https://user-images.githubusercontent.com/17249402/114314081-87c06800-9af9-11eb-8c9c-929cb659b428.png)

Any ideas how to solve?
-- Cor --

**Comment by spudwebb** [comment]
I can reproduce the problem, I'm working on a fix.

**Comment by spudwebb** [comment]
It's fixed in version 1.0.6

**Comment by tonreproc** [comment]
Thanks, I can see now a value appearing below the node. But the values are not updated every time the value changes. I can see in i.e. the Google app MQTTlens that the value changes. So the broker is sending the values all right. 
Is there another problem?

If I select 'Report state on startup' then I see the value in de debug window, but after that no more.

![2021-04-12_171054](https://user-images.githubusercontent.com/17249402/114418662-06c5a700-9bb3-11eb-9790-c38a527f2610.png)

**Comment by spudwebb** [comment]
Do you have the webhook setup correctly in HS4 ?

**Comment by tonreproc** [comment]
well, that was the problem indeed. The webhook has disappeared ??
Now it is working fine, thanks for fixing this.
