### ISSUE TITLE
Ignore "Last" messages when followed by a second

### ISSUE THREAD

**Issue by KSumwalt** [HomeSeer/node-red-contrib-homeseer#15]
When at least a z-wave dimmer switch is set to the "Last" value in the HomeSeer web interface, 2 messages are sent to Node-RED.  One with msg.payload.status = "Last" and second with msg.payload.status set to the dim value.  Is it possible to ignore the first, knowing a second is coming?  I am guessing someone may want this "Last" message as well, so can this be an option?

**Comment by spudwebb** [comment]
This is very specific to the way the Z-Wave plugin handles the "Last" command, so I don't think this is in the scope of this project.
Also I'm sure there is already a lot of ways to ignore this "Last" message in a Node-Red flow.
