### ISSUE TITLE
[Enhancement] Ability to send strings bidirectionally + possibility to send strings/value from an event to NR

### ISSUE THREAD

**Issue by MattL0** [HomeSeer/node-red-contrib-homeseer#4]
The ability to send a string to an hs4 device would be great. 

Also the ability to send an arbitrary value  and string to a node red input node ( form an new hs4 event action) would be very practical . In that case hs4 would need to have a list of the nodered node used, so we can send wtv we want to node-red

**Comment by spudwebb** [comment]
> The ability to send a string to an hs4 device would be great.

this will be done as part of #5

> Also the ability to send an arbitrary value and string to a node red input node ( form an new hs4 event action) would be very practical . In that case hs4 would need to have a list of the nodered node used, so we can send wtv we want to node-red

you can create a virtual device and change its value/status from HS4, and then monitor that device from Node-Red

**Comment by spudwebb** [comment]
with version 1.0.3 you can now update a device status by sending the following to a HS Device node

```
{
    topic: "update",
    payload: {
        status:  "My Status"
    }
}
```
