### ISSUE TITLE
Staus device?

### ISSUE THREAD

**Issue by kimstor1435** [HomeSeer/node-red-contrib-homeseer#7]
It seems tom me that I am not able to get the status from a Homeseer device unless I control it, would love a status node that sends the changes from Homeseer to Nodered.

**Comment by spudwebb** [comment]
have you configured the webhook like explained in the README?
if you do, all status and value changes are sent automatically to the HS Device nodes in Node-Red

**Comment by kimstor1435** [comment]
Yes, but if I hook up a debug node I don`t get any info in the debug node when I change brightness on the switch or in Homeseer

**Comment by kimstor1435** [comment]
Also tried to connect a debug to a homeseer motion sensor, no status is reported to the debug when motion.
I am able to control HS from Nodered, but I want also to know the changes of HS devices in Nodered

**Comment by spudwebb** [comment]
does the yellow status text under the node changes when the status of the device changes in Homeseer?
if not, then you have a problem with the webhook.

**Comment by kimstor1435** [comment]
No, only changes when I do a "deploy" in nodered

**Comment by kimstor1435** [comment]
From Homeseer log:
Posting to webhook failed: Den eksterne serveren returnerte feilen (401) Uautorisert. URL: http://10.1.1.250:1880/homeseer/webhook

**Comment by spudwebb** [comment]
somehow HomeSeer is not authorized to post to Node-Red
If you have enable any kind of security in Node-Red, like user/password authentication, you need to disable it as the HomeSeer webhook does not currently supports this
