### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by papadave1984** [HomeSeer/node-red-contrib-homeseer#8]
Have the possibility for the node to update every time the HomeSeer device is set regardless if the value changed or not. Just like when the HomeSeer device feature “last change time updates on status change only” box is unchecked

**Comment by spudwebb** [comment]
Currently HS4 is only posting device's value or status changes, so the webhook behavior would need to be changed before we can add this feature to the node red integration. I created a feature request for HS4.  (HS-1013)

**Comment by papadave1984** [comment]
Thank you sounds good

**Comment by marc-gist** [comment]
Any news on an HS4 update being done for sure?  This is really needed for Scene controller/switches as if someone presses the same scene button combination as was last used, even days in the past, no update is sent to NodeRed :( 
I'd love to be able to stop using a custom event to send out messages. :)
Thank you!

**Comment by spudwebb** [comment]
A part of this feature needs to be implemented in HS4 itself, so it will take a bit longer.

**Comment by marc-gist** [comment]
> A part of this feature needs to be implemented in HS4 itself, so it will take a bit longer.

I understood that. where can I find details/updates on the HS4 portion?

**Comment by spudwebb** [comment]
I will update you here when I have some news

**Comment by kmitch95120** [comment]
There's a pretty easy work around for this using an HS event.  Take an Aeon Lab Minimote scene controller as an example.  In HS, the HS device that holds the last scene is set to a value between 0-8, with "Ready" being 0 and 1-8 being the requested scene. 

Create an event in HS that triggers whenever the scene device is set and has a value greater than 0 (Ready). Have the event delay for 1-2 seconds and then set the scene device value back to 0.   This will cause HS to send a change to the webhook the next time and every time a scene is set.  In NR, ignore the scene value unless it's greater than 0, unless you want to know that the scene device was reset to Ready.  If you want to preserve the "last scene" have the event copy the value to a virtual device before resetting the scene device to 0.

**Comment by marc-gist** [comment]
@kmitch95120 yes, this is what i have done. but again, I'm hoping for a much cleaner solution.  A simple flag in HA to send all updates to a devices state or value should be available on HS. all other home automation systems i've tried have this.

**Comment by spudwebb** [comment]
This feature request has been implemented in HS 4.1.13.0
Now a "HS Device" is updated when it has its value set even if the value does not change but only if "Last Change Time Updates on Status Change Only" is unchecked.
